import { createChimpbase } from "@chimpbase/bun";
import { action, v } from "@chimpbase/runtime";
const chimpbase = await createChimpbase({ storage: { engine: "memory" }, server: { port: 0 }, telemetry: { persist: { log: true, metric: true, trace: true } } });
const testLogging = action({ name: "testLogging", args: v.object({}), async handler(ctx) { ctx.log.debug("processing started", { orderId: 123 }); ctx.log.info("order created", { orderId: 123, total: 99.99 }); ctx.log.warn("inventory low", { sku: "ABC", remaining: 2 }); ctx.log.error("payment failed", { orderId: 123, reason: "declined" }); return { logged: true }; } });
const testMetrics = action({ name: "testMetrics", args: v.object({}), async handler(ctx) { ctx.metric("orders.created", 1, { region: "us-east" }); ctx.metric("payment.amount", 99.99, { currency: "USD" }); return { metriced: true }; } });
const testTracing = action({ name: "testTracing", args: v.object({}), async handler(ctx) { return await ctx.trace("process-order", async (span) => { span.setAttribute("orderId", "123"); return { traced: true }; }); } });
const noisyAction = action({ name: "noisyAction", args: v.object({ id: v.string() }), telemetry: { log: false }, async handler(ctx, input) { ctx.log.info("not persisted"); return { id: input.id }; } });
chimpbase.register({ testLogging, testMetrics, testTracing, noisyAction }); await chimpbase.start();
console.log("telemetry (logging):", JSON.stringify((await chimpbase.executeAction("testLogging", {})).result));
console.log("telemetry (metrics):", JSON.stringify((await chimpbase.executeAction("testMetrics", {})).result));
console.log("telemetry (tracing):", JSON.stringify((await chimpbase.executeAction("testTracing", {})).result));
console.log("telemetry (per-handler):", JSON.stringify((await chimpbase.executeAction("noisyAction", { id: "test" })).result));
console.log("telemetry: OK"); await chimpbase.close(); process.exit(0);
