import { createChimpbase } from "@chimpbase/bun";
import { plugin, action, worker, subscription, v } from "@chimpbase/runtime";
const chimpbase = await createChimpbase({ storage: { engine: "memory" }, server: { port: 0 } });
const todoPlugin = plugin({ name: "todos" }, action({ name: "createTodoPlugin", args: v.object({ title: v.string() }), async handler(ctx, input) { ctx.pubsub.publish("todo.created", { title: input.title }); return { id: 1, title: input.title }; } }), subscription("todo.created", async (ctx, event: { title: string }) => { await ctx.enqueue("todo.index", event); }, { idempotent: true, name: "indexTodoOnCreate" }), worker("todo.index", async () => {}));
const corePlugin = plugin({ name: "core" }, action({ name: "coreAction", args: v.object({}), async handler() { return { core: true }; } }));
const featurePlugin = plugin({ name: "feature", dependsOn: [corePlugin] }, action({ name: "featureAction", args: v.object({}), async handler() { return { feature: true }; } }));
const anotherPlugin = plugin({ name: "another", dependsOn: ["core"] }, action({ name: "anotherAction", args: v.object({}), async handler() { return { another: true }; } }));
chimpbase.register(todoPlugin, featurePlugin, corePlugin, anotherPlugin); await chimpbase.start();
console.log("plugins (todo):", JSON.stringify((await chimpbase.executeAction("createTodoPlugin", { title: "Test" })).result));
console.log("plugins (core):", JSON.stringify((await chimpbase.executeAction("coreAction", {})).result));
console.log("plugins (feature):", JSON.stringify((await chimpbase.executeAction("featureAction", {})).result));
console.log("plugins: OK"); await chimpbase.close(); process.exit(0);
