import { createChimpbase } from "@chimpbase/bun";
import { action, v } from "@chimpbase/runtime";
const chimpbase = await createChimpbase({ storage: { engine: "memory" }, server: { port: 0 } });
const testKv = action({ name: "testKv", args: v.object({}), async handler(ctx) { await ctx.kv.set("config:feature-flags", { darkMode: true }); const flags = await ctx.kv.get("config:feature-flags"); const keys = await ctx.kv.list({ prefix: "config:" }); await ctx.kv.delete("config:feature-flags"); return { flags, keys }; } });
const testCollections = action({ name: "testCollections", args: v.object({}), async handler(ctx) { const id = await ctx.collection.insert("notes", { title: "Meeting notes", content: "..." }); const notes = await ctx.collection.find("notes", { title: "Meeting notes" }); const recent = await ctx.collection.find("notes", {}, { limit: 10 }); const note = await ctx.collection.findOne("notes", { id }); await ctx.collection.update("notes", { id }, { content: "updated" }); const names = await ctx.collection.list(); await ctx.collection.delete("notes", { id }); return { id, notes: notes.length, recent: recent.length, note: note != null, names }; } });
const testStreams = action({ name: "testStreams", args: v.object({}), async handler(ctx) { await ctx.stream.append("audit.todos", "todo.created", { todoId: 1, createdBy: "user1" }); const events = await ctx.stream.read("audit.todos"); return { events: events.length }; } });
chimpbase.register({ testKv, testCollections, testStreams }); await chimpbase.start();
const r1 = await chimpbase.executeAction("testKv", {}); console.log("state (kv):", JSON.stringify(r1.result));
const r2 = await chimpbase.executeAction("testCollections", {}); console.log("state (collections):", JSON.stringify(r2.result));
const r3 = await chimpbase.executeAction("testStreams", {}); console.log("state (streams):", JSON.stringify(r3.result));
console.log("state: OK"); await chimpbase.close(); process.exit(0);
